// <auto-generated />
namespace ReforcoEF.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ReforcoEF_v4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReforcoEF_v4));
        
        string IMigrationMetadata.Id
        {
            get { return "201807160211464_ReforcoEF_v4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
